# Generated by Django 3.1.4 on 2020-12-28 13:50

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', django.contrib.postgres.fields.citext.CITextField()),
                ('cliente_email', django.contrib.postgres.fields.citext.CIEmailField(max_length=254)),
                ('cliente_senha', models.CharField(max_length=50)),
            ],
        ),
    ]
